### ISSUE TITLE
Implementing USM memory management in dpCtrl

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/pydppl#27]
PyDPPL should expose sycl USM allocators to Python.

What needs to be done?

1. Add a C-API wrapper into `pydppl/backends` for the functions that we need from `cl::sycl::usm`. The C-API will be similar to what we currently have for `cl::sycl::queue` (ref. https://github.com/IntelPython/pydppl/blob/master/backends/include/dppl_sycl_queue_interface.h).

3. We need this so that Sycl headers do not have to be directly included in the Cython extension module and we can use MSVC/GCC to build the extension and link to our helper (libDPPLSyclInteface).

5. Cython extension:

- We need three classes: `MemoryUSMShared`, `MemoryUSMHost`, `MemoryUSMDevice`. Each class corresponds to the three USM memory allocator. 
- `MemoryUSMDevice` should not expose ` __getbuffer__` as Python objects cannot directly use device memory.
-  The `__cinit__` of  the Memory classes perhaps should provide a way to specify the context in which memory is to be allocated. The other option will be to use `dppl.get_current_queue()`. Using the current queue always can lead to programmer errors where he/she tries to use a memory allocated on a given context on a device that is not in that context.
- `MemoryUSMxxx` should provide a factory function to copy data between incompatible device.

**Comment by diptorupd** [comment]
@PokhodenkoSA Look at #30. It introduces changes in how a Sycl queue is stored in dppl. I have added a new class SyclQueue that replaces the previous Py_Capsule. The changes were suggested by @oleksandr-pavlyk to make it easier for us to get the sycl::context from the queue. You can now use SyclQueue::get_sycl_context().get_context_ptr() to get an opaque reference to the context pointer of the queue.

Please use the new SyclQueue class in your memory module.

**Comment by diptorupd** [comment]
Can we expose the USM fine-grained control functions `mem_advise` and `prefetch` in the C API? We might want to use them in Numba.

**Comment by PokhodenkoSA** [comment]
This methods will belong to SyclQueue and will get MemoryUSM classes. Is it correct?
