### ISSUE TITLE
Test cases should skip tests rather than fail if tests run on a system with no OpenCL drivers

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/pydppl#5]
Currently the conda recipe for PyDPPL only works on a system that has OpenCL (both CPU and GPU) drivers installed. The behavior does not allow building the package on a build server with no OpenCL. Should we change the behavior?

**Comment by reazulhoque** [comment]
We should not change this behavior as this does not allow us to test whether the build was successful or not. Closing this issue as this behavior is intended.
