### ISSUE TITLE
build_for_conda.sh is broken

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/pydppl#8]
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-472ea1e140ab> in <module>()
> ----> 1 import dppl.ocldrv
> 
> ~/Desktop/devel/upstream/pydppl/dppl/__init__.py in <module>()
>      49 
>      50 from ._version import get_versions
> ---> 51 from ._oneapi_interface import *
>      52 __version__ = get_versions()['version']
>      53 del get_versions
> 
> ModuleNotFoundError: No module named 'dppl._oneapi_interface'

**Comment by diptorupd** [comment]
@PokhodenkoSA, @reazulhoque  any ideas what might be going wrong?

**Comment by PokhodenkoSA** [comment]
I think `No module named 'dppl._oneapi_interface` shows that cmake did not compile library or place it somewhere not available to Python.

**Comment by PokhodenkoSA** [comment]
I do not use `build_for_conda.sh`. I think I should try to move it to setup.py to use one command: `python setup.py develop` to install it all for development. llvmlite works like this.

**Comment by diptorupd** [comment]
Ok. But, the other script build_for_develop.sh already does that doesn't it?

**Comment by diptorupd** [comment]
build_for_conda.sh is no longer needed and has been removed.
